15r10nk/inline-snapshot

docs/index.md
inline_snapshot/_format.py
inline_snapshot/_inline_snapshot.py
inline_snapshot/_rewrite_code.py
poetry.lock
pyproject.toml
tests/test_pytest_plugin.py

fix: black configuration files are respected

---

CHANGELOG.md
inline_snapshot/__init__.py
inline_snapshot/pytest_plugin.py
pyproject.toml
tests/test_pytest_plugin.py

feat!: removed old --update-snapshots option

---

.github/workflows/ci.yml

ci: use macos-13

---

inline_snapshot/_external.py

Hey, just a quick suggestion, feel free to close or rephrase :smile:

docs: Explain where the external files are saved

---

.pre-commit-config.yaml
docs/extras.md
docs/testing.md
docs/types.md
mkdocs.yml
pyproject.toml
src/inline_snapshot/_types.py
src/inline_snapshot/extras.py
src/inline_snapshot/testing/_example.py
tests/test_docs.py
tests/test_external.py
tests/test_raises.py
tests/utils.py

implement context manager which checks for exceptions
``` python        
def test_raises():
with raises(snapshot("ZeroDivisionError: division by zero")):
1 / 0
```

feat: implement extras.raises

---

.pre-commit-config.yaml
pyproject.toml

* add license metadata to pyproject.toml
* use pre-commit hook to verify pyproject.toml

fix: add license to project metadata and some other fixes

---

docs/third_party.md
mkdocs.yml
pyproject.toml
src/inline_snapshot/_types.py
src/inline_snapshot/extra.py
tests/test_docs.py

prints allows you to snapshot the output of your code.
``` python
from inline_snapshot import snapshot
from inline_snapshot.extra import prints
import sys
def test_prints():
with prints(
stdout=snapshot("hello world\\n"), stderr=snapshot("some error\\n")
):
print("hello world")
print("some error", file=sys.stderr)
```

feat: added extra.prints

---

changelog.d/20240917_192956_15r10nk-git_fix_dirty_equals.md
pyproject.toml
src/inline_snapshot/_inline_snapshot.py
src/inline_snapshot/_rewrite_code.py
src/inline_snapshot/extra.py
src/inline_snapshot/testing/_example.py
tests/conftest.py
tests/test_inline_snapshot.py

fix: dirty_equals can be compared multiple times

---

changelog.d/20240924_150856_15r10nk-git_fix_dirty_equals_bug.md
src/inline_snapshot/_inline_snapshot.py

fix: dirty_equals is an optional dependency

---

changelog.d/20241107_083558_15r10nk-git_tomli.md
pyproject.toml
src/inline_snapshot/_config.py

fix: use tomli instead of toml (#130)

---

changelog.d/20241108_192001_15r10nk-git_fix_cli.md
changelog.d/20241109_074441_15r10nk-git_fix_cli.md
docs/categories.md
docs/configuration.md
docs/eq_snapshot.md
docs/index.md
docs/limitations.md
docs/testing.md
mkdocs.yml
pyproject.toml
src/inline_snapshot/_config.py
src/inline_snapshot/_inline_snapshot.py
src/inline_snapshot/pytest_plugin.py
src/inline_snapshot/testing/_example.py
tests/test_config.py
tests/test_external.py
tests/test_pytest_plugin.py
tests/test_xdist.py

- fix: fix spelling
- fix: --inline-snapshot=create/fix/trim/update does not report other categories
- feat: let tests fail if snapshots where fixed
- feat: command line shortcuts

fix some usability issues

---

pyproject.toml

build: added pytest-mock as explicit dependency

---

.github/workflows/ci.yml
.pre-commit-config.yaml
CHANGELOG.md
changelog.d/20250106_220025_15r10nk-git_format_cmd.md
changelog.d/20250109_071706_15r10nk-git_format_cmd.md
docs/changelog.md
docs/code_generation.md
docs/configuration.md
mkdocs.yml
pyproject.toml
scripts/replace_words.py
src/inline_snapshot/_config.py
src/inline_snapshot/_format.py
src/inline_snapshot/_problems.py
src/inline_snapshot/_rewrite_code.py
src/inline_snapshot/_source_file.py
src/inline_snapshot/_types.py
src/inline_snapshot/_unmanaged.py
src/inline_snapshot/pytest_plugin.py
src/inline_snapshot/testing/_example.py
tests/_is_normalized.py
tests/conftest.py
tests/test_config.py
tests/test_formating.py
tests/test_is_normalized.py

feat: added format-command config option

---

changelog.d/20250115_130342_15r10nk-git_fix_pydantic_ai_errors.md
pyproject.toml
src/inline_snapshot/_adapter/adapter.py
src/inline_snapshot/_adapter/dict_adapter.py
src/inline_snapshot/_adapter/generic_call_adapter.py
src/inline_snapshot/_adapter/sequence_adapter.py
src/inline_snapshot/_adapter/value_adapter.py
src/inline_snapshot/_inline_snapshot.py
src/inline_snapshot/_source_file.py
tests/test_pydantic.py

fix: fixed crash caused by custom factory methods

---

changelog.d/20250331_195954_15r10nk-git_fix_is_repr.md
src/inline_snapshot/_is.py
tests/test_is.py

fix: repr(Is(x)) returns now repr(x) (#217)

---

changelog.d/20250411_085221_15r10nk-git_fix_pytester.md
src/inline_snapshot/_global_state.py
src/inline_snapshot/pytest_plugin.py
tests/test_pytester.py

fix: fixed bug in combination with pytest.pytester (#229)

---

.pre-commit-config.yaml
changelog.d/20250505_221504_15r10nk-git_docs_test.md
conftest.py
src/inline_snapshot/_is.py
src/inline_snapshot/_snapshot/generic_value.py
src/inline_snapshot/_types.py
src/inline_snapshot/_unmanaged.py
src/inline_snapshot/pydantic_fix.py
src/inline_snapshot/testing/_example.py
tests/conftest.py
tests/test_docs.py
tests/test_external.py
tests/test_typing.py

migrated test to `inline_snapshot.testing.Example`.

test: refactored doc tests

---

.github/pull_request_template.md
pyproject.toml

docs: pull-request template

---

docs/limitations.md

I rewrote this page into a more verbose style to better describe the limitations, as I understand them.
n/a
- [n/a] I have added a changelog entry with `hatch run changelog:entry`

Improve Limitations documentation

---

.github/workflows/test_docs.yml
docs/limitations.md

docs: fixed broken link

---

docs/eq_snapshot.md

I have tried to improve this documentation by:
1. Adding more links over to the dirty-equals documentation.
2. Adding more prose to explain how things work.
3. Avoiding tabbed steps because they require the reader to realize the tabs are part of the flow and actively focus and click through them. I think tabs should generally be used for alternatives only, such as between different platforms or languages.
I hope this all makes sense!
n/a

Improve dirty-equals documentation

---

changelog.d/20250715_044615_15r10nk-git_llms_txt.md
mkdocs.yml
pyproject.toml
src/inline_snapshot/_find_external.py

docs: added llms.txt

---

changelog.d/20250725_054715_15r10nk-git_fix_performance.md
src/inline_snapshot/_external/_find_external.py
tests/external/test_external.py

fix: fixed performance of used_externals_in (#272)

---

changelog.d/20250725_151519_15r10nk-git_fix_tmp_path.md
src/inline_snapshot/_external/_external.py
src/inline_snapshot/_external/_external_file.py
src/inline_snapshot/_external/_outsource.py
src/inline_snapshot/_external/_tmp_path.py
src/inline_snapshot/_global_state.py
src/inline_snapshot/pytest_plugin.py

fix: cleanup temporary path

---

src/inline_snapshot/pytest_plugin.py
tests/test_ci.py

A tiny PR that fixes a typo (`snasphot`).
PS. Just started using `inline-snapshot`. Very glad to find a good counterpart for https://github.com/mitsuhiko/insta in the python ecosystem :)

snasphot -> snapshot

---

CHANGELOG.md
scripts/replace_words.py

added issue links to changelog via pre-commit hook

---

docs/configuration.md
mkdocs.yml
src/inline_snapshot/_global_state.py
src/inline_snapshot/pytest_plugin.py

refactor: changed how disabled is implemented

---

.github/workflows/deploy_development_docs.yml
.github/workflows/docs.yml

ci: added mutex to documentation deployment

---

changelog.d/20250810_100822_15r10nk-git_fix_quoting.md
docs/changelog.md
src/inline_snapshot/_source_file.py
tests/test_string.py

fix: do not use tripple quoted strings if not needed (#281)

---

CONTRIBUTING.md
changelog.d/20250724_221515_15r10nk-git_fix_docs.md
docs/testing.md
src/inline_snapshot/testing/_example.py
tests/test_docs.py

docs: improved contributing and testing docs

---

.github/workflows/cog.yml
README.md
pyproject.toml

feat: update sponsors and automate cog:update

---

changelog.d/20250923_080244_15r10nk-git_external_report.md
src/inline_snapshot/_external/_external.py
src/inline_snapshot/_external/_external_base.py
src/inline_snapshot/_external/_external_file.py
src/inline_snapshot/_inline_snapshot.py
src/inline_snapshot/testing/_example.py
tests/external/test_external.py
tests/external/test_external_file.py
tests/test_storage.py

fix: fixed `--inline-snapshot=report` for external and external_file (#298)

---

changelog.d/20251004_090949_15r10nk-git_fix_xdist.md
src/inline_snapshot/pytest_plugin.py
src/inline_snapshot/testing/_example.py
tests/conftest.py
tests/test_xdist.py

fix: fixed xdist check
